#
coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: auto
        threshold: 5 # allow drops by 5 percent
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 0
    changes: false

ignore:
  - "astromodels/tests/*"
  - "astromodels/_version.py"
  - "**/__init__.py"
  - "astromodels/functions/numba_functions.py" # cannot cover jitted code

comment:
    layout: "condensed_header, condensed_files, condensed_footer"
    behavior: default
