{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#  git_url: https://github.com/threeml/{{ name }}.git
  path: ../../

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - xspec==12.15.1 # [not (linux and aarch64)]
    - versioneer
    - setuptools
    - pip
    - numpy

  host:
    - python {{ python }}
    - pip
    - setuptools
    - numpy
    - pyyaml
    - pandas
    - xspec==12.15.1 # [not (linux and aarch64)]
    - future
    - numba
    - h5py>=3.9
    - colorama
    - omegaconf
    - rich
    - joblib
    - versioneer

  run:
    - python
    - numpy
    - pyyaml
    - astropy
    - scipy
    - pytables
    - pandas
    - dill
    - future
    - numba
    - h5py>=3.9
    - colorama
    - omegaconf
    - rich
    - joblib
    - xspec==12.15.1 # [not (linux and aarch64)]    
    - versioneer

build:
  script: $PYTHON -m pip install --verbose --no-deps --ignore-installed .
  skip: true  # [win]

test: # already uses requirements from "run"
  requires:
    - pytest
    - pytest-cov
    - coverage
  source_files:
    - astromodels/tests
    - pyproject.toml # needed for pytest setup e.g. marks
  commands:
    - pytest -vv astromodels/tests --cov=astromodels --cov-report=term

about:
  home: https://github.com/threeml/astromodels
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Models for astronomy and astrophysics
  description: |
    Astromodels contains models to be used in likelihood or 
    Bayesian analysis in astronomy and astrophysics

  dev_url: https://github.com/threeML/astromodels
  doc_url: https://astromodels.readthedocs.io
