{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#  git_url: https://github.com/threeml/{{ name }}.git
  path: ../../

requirements:
  build:
    - {{ compiler('c') }} # [linux]
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('fortran') }} # [linux]
    - xspec-modelsonly
    - cfitsio==3.410
    - ccfits
    - wcslib==5.18
    - krb5==1.14.6
    - readline==6.2 # [py2k]

  host:
    - python
    - setuptools
    - pip
    - numpy
    - pyyaml==3.13
    #- astropy
    #- scipy
#    - numdifftools
    #- hdf5
    #- pytables
    - pandas>=0.23
    - cfitsio==3.410
    - ccfits
    - wcslib==5.18
    - xspec-modelsonly
    - future
    - krb5==1.14.6
    - readline==6.2 # [py2k]
    - numba
    
    - h5py


  run:
    - python
  #  - libgfortran
    - numpy
    - pyyaml==3.13
    - astropy<3.2
    #- scipy
#    - numdifftools
    #- hdf5
    - pytables
    - pandas>=0.23
    - dill
    - cfitsio
    - ccfits
    - wcslib
    - future
    - krb5==1.14.6
    - readline==6.2 # [py2k]
    - numba
    
    - h5py
    - interpolation>=2.1.5 # [py3k]

build:
  script: python -m pip install --verbose --no-deps --ignore-installed .
  skip: true  # [win]
#  skip: true  # [py3k]

#test:
#  # Python imports
#  imports:
#    - astromodels
#    - astromodels.core
#    - astromodels.functions
#    - astromodels.functions.dark_matter
#    - astromodels.sources
#    - astromodels.utils
#    - astromodels.xspec

#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

#  requires:
#    - xspec-modelsonly


about:
  home: https://github.com/threeml/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
