{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
  path: ../../

requirements:
  build:

  host:
    - python {{ python }}
    - setuptools
    - pip
    - numpy
    - pyyaml>=5.3
    - astropy
    #- scipy
    - numdifftools
    #- hdf5
    - pytables
    - pandas
    - future
    - numba
    - h5py>=3.9

  run:
    - python
    - numpy
    - pyyaml
    - astropy
    - numdifftools
    - pytables
    - pandas
    - dill
    - future
    - numba
    - h5py>=3.9
    - rich
    
build:
  script: $PYTHON -m pip install --verbose --no-deps --ignore-installed .
  skip: true

test:
  # Python imports
  imports:
    - astromodels
    - astromodels.core
    - astromodels.functions
    - astromodels.functions.dark_matter
    - astromodels.sources
    - astromodels.utils


#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.



about:
  home: https://github.com/threeml/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
